### ISSUE TITLE
Return QR code for new bot addition

### ISSUE THREAD

**Issue by sherlockparadox** [DerDeathraven/steam-comment-bot-rest-api#9]
Hi there!
Kudos on having a great plugin to allow direct bot push into the queue using API.

As far as  I can see, there currently is a support to directly send steam auth guard code using bot index.
Just wanted to check if there will even be a functionality to login via QR code using the same bot index or get this QR code as response to adding the bot via existing addBot controller?

Thanks & Cheers!

**Comment by 3urobeat** [comment]
Hey, sorry for the *very* late response; both @DerDeathraven and I are currently busy with other projects.

If I recall correctly the bot currently does not send qrcode requests to plugins, only text & number based 2FA codes.  
I'll have to see if and how that could be implemented (and documented).

We'll leave this issue open until then and I will update it when I've got something to share ^^

**Comment by sherlockparadox** [comment]
Hi @3urobeat ! Thank you for your response!

I'm trying to study your code & figure out how to get this done by myself and probably raise a PR here as well. I'm not proficient in js.

Also, is there any way you can spill beans or give a sneak peek on this new project you guys are working on? 😋
Since you guys are pretty much always working on something crazy & fun!

Looking forward to checking out your new projects!
Cheers!

**Comment by 3urobeat** [comment]
Hey, 
if you can figure out how to implement it yourself - sure! I always appreciate any PRs.

I did a quick look at my code, the bot sends normal 2fa codes to all plugins [here](https://github.com/3urobeat/steam-comment-service-bot/blob/724b813666cdd256baea0b243eb0f7a4d4bd0524/src/sessions/helpers/handle2FA.js#L128) and handles QR-Codes [here](https://github.com/3urobeat/steam-comment-service-bot/blob/724b813666cdd256baea0b243eb0f7a4d4bd0524/src/sessions/helpers/handle2FA.js#L169).  
I'm not exactly sure what the best implementation for QR-Codes would be, as we kinda have to indicate to plugins if the incoming request is a normal 2fa code or a QR-Code (maybe with a type param? or an additional function? idk).

Well regarding the other projects, I'm currently working on [git-anon](https://github.com/3urobeat/git-anon) and DerDeathraven at some project for a customer, but I don't know exactly what.

**Comment by 3urobeat** [comment]
The bot now has a steamGuardQrCode event, which can be handled from plugins using the `steamGuardQrCode()` function.  
This plugin now needs to implement the function to make it accessible for applications that implement the API (unless this is already happening automatically?).

**Comment by 3urobeat** [comment]
Sorry for the wait. I have just now added a new `/events` route which allows you to subscribe to events fired by the PluginSystem.

By listening to events (see the code example in the PR) you can now catch the event `steamGuardQrCode`, which includes a `challengeUrl` property.  
You can render this URL as a QR-Code (for example using the `qrcode` library like the bot does). When this QR-Code is scanned using the Steam Mobile App, the login request will resolve and the account will log on.  

This should resolve this issue.

The bot will automatically update this plugin on startup as soon as @DerDeathraven pushed the update to NPM.  
Let me know if I missed something or if you run into issues. Thanks!
